# Nextjs Dockerfile

FROM node:22-alpine

WORKDIR /app
COPY package*.json pnpm-lock.yaml pnpm-workspace.yaml ./

RUN corepack enable

RUN pnpm install --frozen-lockfile

COPY . .

RUN pnpm run build
EXPOSE 3000

CMD [ "pnpm", "start" ]